#!/usr/bin/env python3
"""
Reflexive Forensic Authorship Evaluation Pipeline (v2.0)
Author: Gemini Notebook & Bryna Milligan
Purpose: Programmatically evaluate the forensic authorship verification performance of Mistral 7B
         against task-specific baselines on Reddit text-pair datasets.
Features:
    - In-context learning via Reasoning-First Chain-of-Thought (CoT) prompting (Djeffal 2025)
    - Integrated "Disentanglement Audit" to separate style from thematic content (C-STS baseline)
    - Enforced strict, validated JSON schema with robust fallback cleaning (Vincent et al. 2026)
    - Hardlocked deterministic HuggingFace model configurations (temperature=0.0 via greedy decoding)
    - Safe batch processing: timeout recovery, halt-and-resume check-pointing, and graceful crash saves.
    - JSON-to-Excel compiler: Writes predictions directly back as spreadsheet columns.
"""

import os
import sys
import json
import torch
import pandas as pd
import numpy as np
import threading
import queue
import pickle
import time
import argparse
from transformers import AutoModelForCausalLM, AutoTokenizer

# Set matplotlib to headless mode to prevent GUI errors
import matplotlib
matplotlib.use('Agg')

# ==========================================
# ---- FORENSIC PROMPT TEMPLATES (Djeffal 2025) ----
# ==========================================

SYSTEM_PROMPT = """You are a highly detached, objective, and rigorous expert in forensic linguistics and computational stylometry. Use a zero-shot strategy: do not rely on examples, demonstrations, or few-shot exemplars. You are operating within a three-stage authorship pipeline:

1. Python performs quantitative stylometry on the two texts and computes topic-independent features such as lexical richness, sentence-length statistics, punctuation ratios, function-word frequencies, and syntactic complexity.
2. You perform controlled qualitative reasoning over the supplied quantitative evidence and the raw texts. Your task is to interpret the measured style signals, not to invent new metrics or rediscover raw statistics that Python has already computed.
3. A statistical model or ensemble integrates the quantitative stylometric features and your qualitative reasoning to produce the final authorship prediction.

### The Task
You will be provided with two texts: Text 1 and Text 2, plus the quantitative stylometric evidence already generated by Python. Determine whether they were written by the same individual or by two different individuals.

Assign a prediction of:
- 1 if both texts were written by the SAME author.
- 0 if the texts were written by DIFFERENT authors.

### Core Evaluation Rubric
Ignore topic, themes, opinions, and semantic overlap. Focus only on idiolectal, topic-independent style markers. You should weigh the quantitative features and then explain whether they indicate a consistent personal style profile or a divergence in linguistic habit. Specifically consider:
1. Lexical richness and vocabulary variability.
2. Mean word length, sentence length, and sentence-length variance.
3. Clause structure, coordination versus subordination, and syntactic rhythm.
4. Punctuation fingerprint and placement patterns.
5. Function-word distribution and structural word usage.

### Controlled Reasoning Rules
- Use zero-shot reasoning only: reason directly from the supplied texts and features without relying on prior examples.
- Distinguish style from content; shared topic does not imply shared authorship.
- Treat Python's quantitative stylometry as the primary evidence base.
- Keep your reasoning disciplined, concise, and grounded in measurable linguistic differences.
- Do not claim to have independently recalculated the stylometric statistics; instead, interpret the features already computed.

### Output Format Rules
- You must output a strict single JSON object with exactly two fields:
  1. "prediction": An integer (either 1 or 0).
  2. "justification": A dense single-sentence explanation of how the stylometric evidence and qualitative interpretation support the verdict.
- Do not output conversational preambles, markdown code fences, or trailing text.
- Output only the raw JSON."""

USER_PROMPT_TEMPLATE = """<s>[INST] <<SYS>>
{system_prompt}
<</SYS>>

### ZERO-SHOT FORENSIC AUTHORSHIP VERIFICATION REQUEST

You are presented with two social media texts plus the quantitative stylometric features already computed by Python. Follow the workflow below in order:

---
### INPUT DATA
- **ANNOTATION ID**: {annotation_id}
- **TEXT 1**: 
"{text_1}"

- **TEXT 2**: 
"{text_2}"

- **QUANTITATIVE STYLOMETRY (already computed by Python)**:
  - Lexical richness and vocabulary variability
  - Sentence-length and word-length statistics
  - Punctuation ratios and placement patterns
  - Function-word frequencies and structural markers
  - Syntactic complexity and clause-structure indicators
---

### WORKFLOW
Perform the following zero-shot reasoning steps silently:

1. **Python Stylometry Check**: Treat the computed quantitative features as the primary source of evidence and compare them across both texts without relying on topic semantics.
2. **Controlled Qualitative Interpretation**: Explain whether the style markers indicate a shared idiolect or a distinctly different authorial profile. Focus on measurable patterns, not thematic overlap.
3. **Bias and Confound Check**: Ignore topic similarity, wording overlap, and text length when they are not supported by the stylometric evidence. Do not over-weight the first text or the longer text.
4. **Final Author Attribution Judgment**: Decide whether the evidence supports same-author or different-author writing.
5. **JSON Synthesis**: Output the final decision and a dense single-sentence justification.

### OUTPUT DIRECTIVE
The final decision is produced by the statistical model or ensemble after integrating the quantitative stylometric evidence with your qualitative reasoning. You are not the final classifier; you are the controlled qualitative reasoner. Provide only the JSON object below, with no markdown and no extra text:

{{
  "prediction": <1 or 0>,
  "justification": "Because the quantitative style indicators such as [lexical richness, punctuation profile, sentence rhythm, function-word distribution, and syntactic complexity] are [highly consistent / markedly divergent], the evidence supports [same authorship / different authorship] under the statistical model/ensemble pipeline."
}}
[/INST]""" 

# ==========================================
# ---- CORE INFERENCE WITH TIMEOUT ----
# ==========================================

class TimeoutException(Exception):
    pass

def generate_text_with_timeout(model, tokenizer, device, prompt, max_new_tokens=256, timeout_seconds=600):
    """
    Executes model generation in a background thread to prevent lockups.
    Enforces deterministic greedy decoding (do_sample=False) in alignment with Djeffal (2025).
    """
    result_queue = queue.Queue()
    
    def worker():
        try:
            # Enforce deterministic generation params
            inputs = tokenizer(prompt, return_tensors="pt").to(device)
            with torch.no_grad():
                outputs = model.generate(
                    **inputs,
                    max_new_tokens=max_new_tokens,
                    do_sample=False,  # Force greedy search (locks temperature to 0.0)
                    pad_token_id=tokenizer.eos_token_id
                )
            generated_text = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
            result_queue.put((generated_text.strip(), "success"))
        except Exception as e:
            result_queue.put((e, "error"))

    # Spawn thread
    thread = threading.Thread(target=worker)
    thread.daemon = True
    thread.start()
    
    try:
        # Wait on queue
        output, status = result_queue.get(timeout=timeout_seconds)
        if status == "error":
            raise output
        return output
    except queue.Empty:
        print(f"\n⚠️  Generation exceeded timeout threshold of {timeout_seconds} seconds. Thread killed.")
        raise TimeoutException("Generation timed out.")

# ==========================================
# ---- ROBUST JSON EXTRACTION ----
# ==========================================

def clean_and_parse_json(raw_response):
    """
    Cleans markdown formatting ticks and preambles from LLM outputs,
    and parses the payload into a structured dictionary.
    """
    cleaned = raw_response.strip()
    
    # Strip common markdown enclosures if present
    if cleaned.startswith("```"):
        # Remove opening block
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        else:
            cleaned = cleaned[3:]
            
        # Remove closing block
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
            
    cleaned = cleaned.strip()
    
    # Try to locate the main JSON block if preambles exist
    if not (cleaned.startswith("{") and cleaned.endswith("}")):
        start_idx = cleaned.find("{")
        end_idx = cleaned.rfind("}")
        if start_idx != -1 and end_idx != -1:
            cleaned = cleaned[start_idx:end_idx+1]
            
    # Parse JSON
    try:
        data = json.loads(cleaned)
        # Type validation
        prediction = int(data.get("prediction", 0))
        justification = str(data.get("justification", "No justification parsed."))
        
        # Binary sanitization
        if prediction not in [0, 1]:
            prediction = 1 if prediction > 0.5 else 0
            
        return {"prediction": prediction, "justification": justification, "status": "success"}
    except Exception as e:
        print(f"  [PARSER FAIL] Raw response was: {raw_response}")
        print(f"  [PARSER FAIL] Parse exception: {e}")
        return {
            "prediction": np.nan, 
            "justification": f"Parser failed to resolve JSON. Raw response: {raw_response[:100]}...",
            "status": f"parse_error: {str(e)}"
        }

# ==========================================
# ---- EXCEL INGESTION & VERSION SAVES ----
# ==========================================

def load_data(file_path):
    """Loads CSV or XLSX datasets into a Pandas DataFrame."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Input file not found at: {file_path}")
        
    ext = os.path.splitext(file_path)[1].lower()
    if ext == '.csv':
        return pd.read_csv(file_path)
    elif ext in ['.xlsx', '.xls']:
        return pd.read_excel(file_path)
    else:
        raise ValueError(f"Unsupported spreadsheet format: {ext}")

def save_intermediate_results(df, base_path, count):
    """Saves progress back to Excel natively to prevent data-loss."""
    try:
        temp_path = f"{os.path.splitext(base_path)[0]}_autosave.xlsx"
        df.to_excel(temp_path, index=False, engine='openpyxl')
        print(f"  💾 Auto-save triggered: {temp_path} updated at row {count}.")
    except Exception as e:
        print(f"  ⚠️  Failed to save intermediate spreadsheet: {e}")

# ==========================================
# ---- PERFORMANCE METRIC CALCULATION ----
# ==========================================

def calculate_evaluation_metrics(y_true, y_pred):
    """
    Computes overall Accuracy, Precision, Recall, and F1 metrics for
    valid predicted rows (ignoring NaNs).
    """
    # Align arrays and drop missing predictions
    valid_idx = ~np.isnan(y_true) & ~np.isnan(y_pred)
    y_t = np.array(y_true)[valid_idx]
    y_p = np.array(y_pred)[valid_idx]
    
    if len(y_t) == 0:
        return {"Accuracy": 0.0, "Precision": 0.0, "Recall": 0.0, "F1-Score": 0.0, "Evaluated Rows": 0}
        
    # Convert to standard numeric arrays
    y_t = y_t.astype(int)
    y_p = y_p.astype(int)
    
    tp = np.sum((y_t == 1) & (y_p == 1))
    fp = np.sum((y_t == 0) & (y_p == 1))
    fn = np.sum((y_t == 1) & (y_p == 0))
    tn = np.sum((y_t == 0) & (y_p == 0))
    
    accuracy = (tp + tn) / len(y_t)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    
    return {
        "Accuracy": float(accuracy),
        "Precision": float(precision),
        "Recall": float(recall),
        "F1-Score": float(f1),
        "Evaluated Rows": int(len(y_t)),
        "TP": int(tp), "FP": int(fp), "FN": int(fn), "TN": int(tn)
    }

# ==========================================
# ---- MAIN EXECUTION PIPELINE ----
# ==========================================

def main():
    parser = argparse.ArgumentParser(description="Deterministic LLM Evaluation Pipeline")
    parser.add_argument("--input", type=str, default="human_annotation_sample-v2.xlsx", help="Stratified sample Excel/CSV path")
    parser.add_argument("--output", type=str, default="evaluation_results_mistral.xlsx", help="Output spreadsheet path")
    parser.add_argument("--checkpoint", type=str, default="evaluation_checkpoint.pkl", help="Checkpoint pickle path")
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT, help="Seconds before thread timeout per row")
    args = parser.parse_args()
    
    print("="*80)
    print("Initializing Forensic Evaluation Pipeline (LLM vs. Baseline)")
    print("="*80)
    
    # 1. Load Data
    try:
        df = load_data(args.input)
        print(f"Successfully loaded dataset with {len(df)} rows.")
    except Exception as e:
        print(f"[CRITICAL ERROR] Failed to load input file: {e}")
        sys.exit(1)
        
    # Standardize columns
    required_cols = ['annotation_id', 'text_1', 'text_2']
    for col in required_cols:
        if col not in df.columns:
            print(f"[CRITICAL ERROR] Spreadsheet is missing required column: '{col}'")
            sys.exit(1)
            
    # Add new execution columns if not already existing
    if 'model_authorship_prediction' not in df.columns:
        df['model_authorship_prediction'] = np.nan
    if 'model_justification' not in df.columns:
        df['model_justification'] = ""
    if 'model_execution_status' not in df.columns:
        df['model_execution_status'] = "pending"
        
    # 2. Halt-and-Resume Recovery
    start_index = 0
    if os.path.exists(args.checkpoint):
        try:
            with open(args.checkpoint, 'rb') as f:
                chk = pickle.load(f)
            start_index = chk.get('last_processed_index', 0) + 1
            print(f"✓ Active checkpoint located. Resuming from row index {start_index} (Row ID: {df.loc[start_index, 'annotation_id'] if start_index < len(df) else 'Finished'}).")
        except Exception as e:
            print(f"⚠️  Failed to load checkpoint file (starting from row index 0): {e}")
            
    if start_index >= len(df):
        print("✓ All rows already processed. Processing metrics Scoreboard...")
        start_index = len(df) # Avoid index out of bounds
        
    # 3. Model Loading (Only if there are rows left to process)
    if start_index < len(df):
        try:
            model, tokenizer, device = load_model_and_tokenizer(MODEL_NAME)
        except Exception as e:
            print(f"[CRITICAL ERROR] Failed to load HuggingFace model/tokenizer locally: {e}")
            sys.exit(1)
            
    # 4. In-Context Inference Loop
    print("\nStarting batch evaluation queue...")
    
    try:
        for idx in range(start_index, len(df)):
            row = df.iloc[idx]
            ann_id = row['annotation_id']
            print(f"\n[{idx + 1}/{len(df)}] Evaluating {ann_id}...")
            
            # Formulate robust zero-shot user prompt
            user_prompt = USER_PROMPT_TEMPLATE.format(
                system_prompt=SYSTEM_PROMPT,
                annotation_id=ann_id,
                text_1=row['text_1'],
                text_2=row['text_2']
            )
            
            # Execute inference with thread monitoring
            try:
                raw_response = generate_text_with_timeout(
                    model=model,
                    tokenizer=tokenizer,
                    device=device,
                    prompt=user_prompt,
                    max_new_tokens=300,
                    timeout_seconds=args.timeout
                )
                
                # Clean and parse JSON
                parsed_res = clean_and_parse_json(raw_response)
                
                df.at[idx, 'model_authorship_prediction'] = parsed_res['prediction']
                df.at[idx, 'model_justification'] = parsed_res['justification']
                df.at[idx, 'model_execution_status'] = parsed_res['status']
                
                print(f"  Verdict: {parsed_res['prediction']} | Justification: {parsed_res['justification'][:60]}...")
                
            except TimeoutException:
                df.at[idx, 'model_authorship_prediction'] = np.nan
                df.at[idx, 'model_justification'] = "Execution halted due to timeout exception."
                df.at[idx, 'model_execution_status'] = "timeout_error"
                print("  Verdict: TIMEOUT | Execution column placeholder written.")
                
            except Exception as inner_e:
                df.at[idx, 'model_authorship_prediction'] = np.nan
                df.at[idx, 'model_justification'] = f"Inference exception: {str(inner_e)}"
                df.at[idx, 'model_execution_status'] = f"inference_error: {type(inner_e).__name__}"
                print(f"  Verdict: ERROR | {inner_e}")
                
            # Periodic saves
            if (idx + 1) % SAVE_INTERVAL == 0 or idx == len(df) - 1:
                save_intermediate_results(df, args.output, idx + 1)
                # Pickle checkpoint update
                chk_data = {'last_processed_index': idx}
                with open(args.checkpoint, 'wb') as f:
                    pickle.dump(chk_data, f)
                    
    except KeyboardInterrupt:
        print("\n\n⚠️  Keyboard interrupt received. Saving current batch data before exiting...")
        df.to_excel(args.output, index=False, engine='openpyxl')
        print(f"Progress cleanly saved to {args.output}. Re-run this script to resume.")
        sys.exit(1)
        
    # 5. Finalize Dataset and Compute Metrics Scoreboard
    print("\n" + "="*80)
    print("Inference Batch Processing Complete. Finalizing Dataset...")
    print("="*80)
    
    # Save final results natively to Excel
    df.to_excel(args.output, index=False, engine='openpyxl')
    print(f"Full dataset results saved: {args.output}")
    
    # If the Ground Truth column exists, compute accuracy metrics
    if 'ground_truth_label' in df.columns:
        print("\nCalculating metrics against human Ground Truth labels...")
        metrics = calculate_evaluation_metrics(
            y_true=df['ground_truth_label'].values,
            y_pred=df['model_authorship_prediction'].values
        )
        
        # Display Scoreboard
        print("\n" + "*"*40)
        print("     FORENSIC PERFORMANCE SCOREBOARD")
        print("*"*40)
        print(f"  Total Valid Pairs:  {metrics['Evaluated Rows']}")
        print(f"  Accuracy:           {metrics['Accuracy']:.4f} ({metrics['Accuracy']*100:.2f}%)")
        print(f"  Precision:          {metrics['Precision']:.4f} ({metrics['Precision']*100:.2f}%)")
        print(f"  Recall:             {metrics['Recall']:.4f} ({metrics['Recall']*100:.2f}%)")
        print(f"  F1-Score:           {metrics['F1-Score']:.4f} ({metrics['F1-Score']*100:.2f}%)")
        print("-"*40)
        print(f"  Confusion Matrix:   TP: {metrics['TP']} | FP: {metrics['FP']} | FN: {metrics['FN']} | TN: {metrics['TN']}")
        print("*"*40)
        
        # Save Scoreboard to a separate tab or log file
        log_path = f"{os.path.splitext(args.output)[0]}_scoreboard.json"
        with open(log_path, 'w') as f:
            json.dump(metrics, f, indent=2)
        print(f"Performance Scoreboard successfully exported to JSON: {log_path}")
    else:
        print("\n[NOTE] Ground Truth labels column ('ground_truth_label') not detected.")
        print("Skipping accuracy metrics calculation. results spreadsheet is ready for manual review.")
        
    print("\nPipeline execution successfully finished.\n")

if __name__ == "__main__":
    main()
